version: "3.8"
services:

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  api_real_estate:
    build: .
    volumes:
      - .:/app
    ports:
      - "5050:5000"
    container_name: api_service

volumes:
  mysql_data: